# Generated by Django 5.0.2 on 2024-02-24 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("discription", models.TextField(blank=True, null=True)),
                ("source_link", models.CharField(max_length=2000)),
                ("demo_link", models.CharField(blank=True, max_length=2000, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
