# Generated by Django 5.0.2 on 2024-02-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_tag_project_vote_ratio_project_vote_total_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="amazon_links_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("projuct_link", models.TextField(max_length=2000)),
            ],
        ),
    ]
